import type { ReactNode } from 'react';

/** A small, purpose-built Markdown renderer for the research note (5.1).
 *
 * The note is deterministically generated by the backend with a known, narrow subset of Markdown —
 * headers, GFM tables, bold/italic, blockquotes, task/plain lists, horizontal rules — so a focused
 * renderer styled with the app's design tokens reads cleaner (and stays more on-brand) than a generic
 * library's defaults. Not a general Markdown engine; it covers exactly what the note emits. */
export default function Markdown({ source }: { source: string }) {
  const lines = source.replace(/\r\n/g, '\n').split('\n');
  const blocks: ReactNode[] = [];
  let i = 0;
  let key = 0;

  const isTableSep = (s: string) => /^\s*\|?[\s:|-]*-[\s:|-]*\|?\s*$/.test(s) && s.includes('-');
  const splitRow = (s: string) =>
    s.trim().replace(/^\|/, '').replace(/\|$/, '').split('|').map((c) => c.trim());

  while (i < lines.length) {
    const line = lines[i];

    // Blank line
    if (line.trim() === '') { i++; continue; }

    // Horizontal rule
    if (/^---+\s*$/.test(line)) {
      blocks.push(<hr key={key++} style={{ border: 0, borderTop: '1px solid var(--color-rule)', margin: '18px 0' }} />);
      i++; continue;
    }

    // Headers
    const h = line.match(/^(#{1,4})\s+(.*)$/);
    if (h) {
      const level = h[1].length;
      const sizes = [20, 15.5, 13.5, 12.5];
      blocks.push(
        <div key={key++} style={{
          fontSize: sizes[level - 1], fontWeight: level <= 2 ? 700 : 600,
          color: 'var(--color-ink)', margin: level === 1 ? '0 0 4px' : '20px 0 8px',
          letterSpacing: level === 1 ? '-.01em' : 0,
          borderBottom: level === 2 ? '1px solid var(--color-rule-soft)' : undefined,
          paddingBottom: level === 2 ? 6 : 0,
        }}>
          {inline(line.replace(/^#{1,4}\s+/, ''))}
        </div>,
      );
      i++; continue;
    }

    // Blockquote
    if (line.startsWith('>')) {
      const quote: string[] = [];
      while (i < lines.length && lines[i].startsWith('>')) { quote.push(lines[i].replace(/^>\s?/, '')); i++; }
      blocks.push(
        <blockquote key={key++} style={{
          margin: '10px 0', padding: '8px 14px', borderLeft: '3px solid var(--color-ink-3)',
          background: 'var(--color-surface-2)', color: 'var(--color-ink-2)', fontSize: 13, lineHeight: 1.6,
        }}>
          {inline(quote.join(' '))}
        </blockquote>,
      );
      continue;
    }

    // Table (a row line immediately followed by a separator line)
    if (line.includes('|') && i + 1 < lines.length && isTableSep(lines[i + 1])) {
      const header = splitRow(line);
      i += 2; // skip header + separator
      const rows: string[][] = [];
      while (i < lines.length && lines[i].includes('|') && lines[i].trim() !== '') {
        rows.push(splitRow(lines[i])); i++;
      }
      blocks.push(
        <div key={key++} style={{ overflowX: 'auto', margin: '10px 0' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12.5 }}>
            <thead>
              <tr>
                {header.map((c, j) => (
                  <th key={j} style={{
                    textAlign: j === 0 ? 'left' : 'right', padding: '6px 12px 6px 0',
                    color: 'var(--color-ink-3)', fontWeight: 600, fontSize: 11,
                    borderBottom: '1px solid var(--color-rule)', whiteSpace: 'nowrap',
                  }}>{inline(c)}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {rows.map((r, ri) => (
                <tr key={ri}>
                  {r.map((c, j) => (
                    <td key={j} style={{
                      textAlign: j === 0 ? 'left' : 'right', padding: '6px 12px 6px 0',
                      color: j === 0 ? 'var(--color-ink)' : 'var(--color-ink-2)',
                      fontFamily: j === 0 ? undefined : 'var(--font-mono)',
                      borderBottom: '1px solid var(--color-rule-soft)', whiteSpace: 'nowrap',
                    }}>{inline(c)}</td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>,
      );
      continue;
    }

    // List (consecutive "- " items, including "- [ ]" task items)
    if (/^\s*-\s+/.test(line)) {
      const items: ReactNode[] = [];
      while (i < lines.length && /^\s*-\s+/.test(lines[i])) {
        let text = lines[i].replace(/^\s*-\s+/, '');
        let box: ReactNode = null;
        const task = text.match(/^\[( |x|X)\]\s+(.*)$/);
        if (task) {
          const checked = task[1].toLowerCase() === 'x';
          box = (
            <span style={{
              display: 'inline-block', width: 12, height: 12, marginRight: 8, borderRadius: 3,
              border: '1.5px solid var(--color-ink-3)', verticalAlign: 'middle',
              background: checked ? 'var(--color-ink-3)' : 'transparent',
            }} />
          );
          text = task[2];
        }
        items.push(
          <li key={items.length} style={{ margin: '4px 0', lineHeight: 1.55, listStyle: task ? 'none' : undefined }}>
            {box}{inline(text)}
          </li>,
        );
        i++;
      }
      blocks.push(
        <ul key={key++} style={{ margin: '8px 0', paddingLeft: 20, fontSize: 12.5, color: 'var(--color-ink-2)' }}>
          {items}
        </ul>,
      );
      continue;
    }

    // Paragraph (gather until blank line or a block starter)
    const para: string[] = [];
    while (i < lines.length && lines[i].trim() !== '' && !/^(#{1,4}\s|>|---+\s*$|\s*-\s)/.test(lines[i])
           && !(lines[i].includes('|') && i + 1 < lines.length && isTableSep(lines[i + 1]))) {
      para.push(lines[i]); i++;
    }
    blocks.push(
      <p key={key++} style={{ margin: '8px 0', fontSize: 12.5, lineHeight: 1.65, color: 'var(--color-ink-2)' }}>
        {inline(para.join(' '))}
      </p>,
    );
  }

  return <div>{blocks}</div>;
}

/** Inline formatting: **bold** and *italic* (bold first so ** isn't eaten by the * rule). */
function inline(text: string): ReactNode[] {
  const out: ReactNode[] = [];
  // Tokenize on **...** and *...*
  const re = /\*\*([^*]+)\*\*|\*([^*]+)\*/g;
  let last = 0;
  let m: RegExpExecArray | null;
  let k = 0;
  while ((m = re.exec(text)) !== null) {
    if (m.index > last) out.push(text.slice(last, m.index));
    if (m[1] !== undefined) {
      out.push(<strong key={k++} style={{ color: 'var(--color-ink)', fontWeight: 600 }}>{m[1]}</strong>);
    } else {
      out.push(<em key={k++} style={{ color: 'var(--color-ink-3)' }}>{m[2]}</em>);
    }
    last = m.index + m[0].length;
  }
  if (last < text.length) out.push(text.slice(last));
  return out;
}
