"""Add summary JSONB column to earnings_transcripts

Revision ID: 4cc0d92dd20c
Revises: 67aec4ab4081
Create Date: 2026-05-03 04:25:59.194982
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cc0d92dd20c'
down_revision: Union[str, None] = '67aec4ab4081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('earnings_transcripts', sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('earnings_transcripts', 'summary')
    # ### end Alembic commands ###
