"""Add earnings_transcripts, analyst_estimates tables and surprise columns

Revision ID: 67aec4ab4081
Revises: a373e00ed4ca
Create Date: 2026-04-27 03:32:54.906481
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67aec4ab4081'
down_revision: Union[str, None] = 'a373e00ed4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst_estimates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('eps_consensus', sa.Float(), nullable=True),
    sa.Column('eps_high', sa.Float(), nullable=True),
    sa.Column('eps_low', sa.Float(), nullable=True),
    sa.Column('revenue_consensus', sa.Float(), nullable=True),
    sa.Column('revenue_high', sa.Float(), nullable=True),
    sa.Column('revenue_low', sa.Float(), nullable=True),
    sa.Column('number_of_analysts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'period_end_date', name='uq_est_ticker_period')
    )
    op.create_index(op.f('ix_analyst_estimates_period_end_date'), 'analyst_estimates', ['period_end_date'], unique=False)
    op.create_index(op.f('ix_analyst_estimates_ticker'), 'analyst_estimates', ['ticker'], unique=False)
    op.create_table('earnings_transcripts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('transcript_date', sa.Date(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('prepared_remarks', sa.Text(), nullable=True),
    sa.Column('qa_section', sa.Text(), nullable=True),
    sa.Column('speakers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'year', 'quarter', name='uq_transcript_ticker_yr_q')
    )
    op.create_index(op.f('ix_earnings_transcripts_ticker'), 'earnings_transcripts', ['ticker'], unique=False)
    op.add_column('earnings_events', sa.Column('eps_surprise_pct', sa.Float(), nullable=True))
    op.add_column('earnings_events', sa.Column('revenue_surprise_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('earnings_events', 'revenue_surprise_pct')
    op.drop_column('earnings_events', 'eps_surprise_pct')
    op.drop_index(op.f('ix_earnings_transcripts_ticker'), table_name='earnings_transcripts')
    op.drop_table('earnings_transcripts')
    op.drop_index(op.f('ix_analyst_estimates_ticker'), table_name='analyst_estimates')
    op.drop_index(op.f('ix_analyst_estimates_period_end_date'), table_name='analyst_estimates')
    op.drop_table('analyst_estimates')
    # ### end Alembic commands ###
