"""initial schema

Revision ID: 6e71872b470c
Revises: 
Create Date: 2026-04-13 06:15:51.833029
"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e71872b470c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_reports_run_date'), 'analysis_reports', ['run_date'], unique=False)
    op.create_index(op.f('ix_analysis_reports_ticker'), 'analysis_reports', ['ticker'], unique=False)
    op.create_table('daily_prices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_price_ticker_date')
    )
    op.create_index(op.f('ix_daily_prices_date'), 'daily_prices', ['date'], unique=False)
    op.create_index(op.f('ix_daily_prices_ticker'), 'daily_prices', ['ticker'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_date'), 'documents', ['date'], unique=False)
    op.create_index(op.f('ix_documents_ticker'), 'documents', ['ticker'], unique=False)
    op.create_table('earnings_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('eps_estimate', sa.Float(), nullable=True),
    sa.Column('eps_actual', sa.Float(), nullable=True),
    sa.Column('revenue_estimate', sa.Float(), nullable=True),
    sa.Column('revenue_actual', sa.Float(), nullable=True),
    sa.Column('guidance_direction', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'report_date', name='uq_earn_ticker_date')
    )
    op.create_index(op.f('ix_earnings_events_report_date'), 'earnings_events', ['report_date'], unique=False)
    op.create_index(op.f('ix_earnings_events_ticker'), 'earnings_events', ['ticker'], unique=False)
    op.create_table('financials',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('gross_profit', sa.Float(), nullable=True),
    sa.Column('operating_income', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('free_cash_flow', sa.Float(), nullable=True),
    sa.Column('operating_cash_flow', sa.Float(), nullable=True),
    sa.Column('total_debt', sa.Float(), nullable=True),
    sa.Column('cash_and_equivalents', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('total_equity', sa.Float(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'period_end_date', name='uq_fin_ticker_period')
    )
    op.create_index(op.f('ix_financials_ticker'), 'financials', ['ticker'], unique=False)
    op.create_table('insider_trades',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('insider_name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('trade_type', sa.String(length=20), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insider_trades_date'), 'insider_trades', ['date'], unique=False)
    op.create_index(op.f('ix_insider_trades_ticker'), 'insider_trades', ['ticker'], unique=False)
    op.create_table('quant_features',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('feature_value', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', 'feature_name', name='uq_qf_ticker_date_feature')
    )
    op.create_index(op.f('ix_quant_features_date'), 'quant_features', ['date'], unique=False)
    op.create_index(op.f('ix_quant_features_ticker'), 'quant_features', ['ticker'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('segment_name', sa.String(length=200), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('growth_yoy', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'period_end_date', 'segment_name', name='uq_seg_ticker_period_name')
    )
    op.create_index(op.f('ix_segments_ticker'), 'segments', ['ticker'], unique=False)
    op.create_table('stock_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('growth_score', sa.Float(), nullable=False),
    sa.Column('profitability_score', sa.Float(), nullable=False),
    sa.Column('valuation_score', sa.Float(), nullable=False),
    sa.Column('momentum_score', sa.Float(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('event_score', sa.Float(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('signal', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_score_ticker_date')
    )
    op.create_index(op.f('ix_stock_scores_date'), 'stock_scores', ['date'], unique=False)
    op.create_index(op.f('ix_stock_scores_ticker'), 'stock_scores', ['ticker'], unique=False)
    op.create_table('stocks',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('added_date', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocks')
    op.drop_index(op.f('ix_stock_scores_ticker'), table_name='stock_scores')
    op.drop_index(op.f('ix_stock_scores_date'), table_name='stock_scores')
    op.drop_table('stock_scores')
    op.drop_index(op.f('ix_segments_ticker'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_quant_features_ticker'), table_name='quant_features')
    op.drop_index(op.f('ix_quant_features_date'), table_name='quant_features')
    op.drop_table('quant_features')
    op.drop_index(op.f('ix_insider_trades_ticker'), table_name='insider_trades')
    op.drop_index(op.f('ix_insider_trades_date'), table_name='insider_trades')
    op.drop_table('insider_trades')
    op.drop_index(op.f('ix_financials_ticker'), table_name='financials')
    op.drop_table('financials')
    op.drop_index(op.f('ix_earnings_events_ticker'), table_name='earnings_events')
    op.drop_index(op.f('ix_earnings_events_report_date'), table_name='earnings_events')
    op.drop_table('earnings_events')
    op.drop_index(op.f('ix_documents_ticker'), table_name='documents')
    op.drop_index(op.f('ix_documents_date'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_daily_prices_ticker'), table_name='daily_prices')
    op.drop_index(op.f('ix_daily_prices_date'), table_name='daily_prices')
    op.drop_table('daily_prices')
    op.drop_index(op.f('ix_analysis_reports_ticker'), table_name='analysis_reports')
    op.drop_index(op.f('ix_analysis_reports_run_date'), table_name='analysis_reports')
    op.drop_table('analysis_reports')
    # ### end Alembic commands ###
