"""add stock_decisions table

Revision ID: a373e00ed4ca
Revises: e1a312a426bc
Create Date: 2026-04-15 05:50:48.811928
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a373e00ed4ca'
down_revision: Union[str, None] = 'e1a312a426bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_decisions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('raw_signal', sa.String(length=20), nullable=False),
    sa.Column('raw_composite', sa.Float(), nullable=False),
    sa.Column('final_signal', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('risk_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasoning', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_decision_ticker_date')
    )
    op.create_index(op.f('ix_stock_decisions_date'), 'stock_decisions', ['date'], unique=False)
    op.create_index(op.f('ix_stock_decisions_ticker'), 'stock_decisions', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_decisions_ticker'), table_name='stock_decisions')
    op.drop_index(op.f('ix_stock_decisions_date'), table_name='stock_decisions')
    op.drop_table('stock_decisions')
    # ### end Alembic commands ###
