"""add valuations table

Revision ID: e1a312a426bc
Revises: 6e71872b470c
Create Date: 2026-04-14 03:48:58.967296
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a312a426bc'
down_revision: Union[str, None] = '6e71872b470c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('valuations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('forward_pe', sa.Float(), nullable=True),
    sa.Column('trailing_pe', sa.Float(), nullable=True),
    sa.Column('peg_ratio', sa.Float(), nullable=True),
    sa.Column('price_to_sales', sa.Float(), nullable=True),
    sa.Column('price_to_book', sa.Float(), nullable=True),
    sa.Column('ev_to_revenue', sa.Float(), nullable=True),
    sa.Column('ev_to_ebitda', sa.Float(), nullable=True),
    sa.Column('trailing_eps', sa.Float(), nullable=True),
    sa.Column('forward_eps', sa.Float(), nullable=True),
    sa.Column('earnings_growth', sa.Float(), nullable=True),
    sa.Column('revenue_growth', sa.Float(), nullable=True),
    sa.Column('gross_margins', sa.Float(), nullable=True),
    sa.Column('operating_margins', sa.Float(), nullable=True),
    sa.Column('profit_margins', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('enterprise_value', sa.Float(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_val_ticker_date')
    )
    op.create_index(op.f('ix_valuations_date'), 'valuations', ['date'], unique=False)
    op.create_index(op.f('ix_valuations_ticker'), 'valuations', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_valuations_ticker'), table_name='valuations')
    op.drop_index(op.f('ix_valuations_date'), table_name='valuations')
    op.drop_table('valuations')
    # ### end Alembic commands ###
